export const hospitalIcon = new URL('../../assets/transport/hospital.svg', import.meta.url).href
export const reportIcon = new URL('../../assets/transport/report.svg', import.meta.url).href
export const chevronIcon = new URL('../../assets/transport/chevron.svg', import.meta.url).href
export const ambulanceImage = new URL('../../assets/transport/ambulance.png', import.meta.url).href
export const herePinIcon = new URL('../../assets/transport/here-pin.svg', import.meta.url).href
export const carIcon = new URL('../../assets/transport/car.svg', import.meta.url).href
export const destinationDotIcon = new URL('../../assets/transport/destination-dot.svg', import.meta.url).href
export const panelCarIcon = new URL('../../assets/transport/panel-car.svg', import.meta.url).href
export const clapIcon = new URL('../../assets/transport/clap.svg', import.meta.url).href
export const checkBoxFillIcon = new URL('../../assets/transport/check-box-fill.svg', import.meta.url).href
export const checkBoxIcon = new URL('../../assets/transport/check-box.svg', import.meta.url).href
export const noTransferEmojiIcon = 'https://www.figma.com/api/mcp/asset/11644d14-98a3-45b6-95f9-aa05ed4aa78f.svg'
export const navReportIcon = new URL('../../assets/transport/nav-report.svg', import.meta.url).href
export const navReportFillIcon = new URL('../../assets/transport/nav-report-fill.svg', import.meta.url).href
export const navHospitalIcon = new URL('../../assets/transport/nav-hospital.svg', import.meta.url).href
export const navHospitalFillIcon = new URL('../../assets/transport/nav-hospital-fill.svg', import.meta.url).href
export const navCarIcon = new URL('../../assets/transport/nav-car.svg', import.meta.url).href
export const navCarFillIcon = new URL('../../assets/transport/nav-car-fill.svg', import.meta.url).href
export const navSettingIcon = new URL('../../assets/transport/nav-setting.svg', import.meta.url).href
export const navSettingFillIcon = new URL('../../assets/transport/nav-setting-fill.svg', import.meta.url).href
export const settingsAlarmIcon = new URL('../../assets/transport/settings-alarm.svg', import.meta.url).href
export const settingsHospitalInfoIcon = 'https://www.figma.com/api/mcp/asset/2c7e5300-8397-4873-b2d4-9765d3c6027d.svg'
export const settingsProfileEditIcon = new URL('../../assets/transport/settings-uiw-setting-o.svg', import.meta.url).href
export const settingsProfileHeadIcon = 'https://www.figma.com/api/mcp/asset/5e1005e7-c3c2-4ae4-be63-757e6e88f017.svg'
export const settingsProfileBodyIcon = 'https://www.figma.com/api/mcp/asset/9ecd133d-5377-4353-aa37-8ab6b2037c34.svg'
export const settingsInformationIcon = new URL('../../assets/transport/settings-information.svg', import.meta.url).href
export const settingsDropdownIcon = new URL('../../assets/transport/settings-dropdown.svg', import.meta.url).href
export const settingsCameraIcon = new URL('../../assets/transport/settings-camera.svg', import.meta.url).href
export const settingsPlusIcon = new URL('../../assets/transport/settings-plus.svg', import.meta.url).href
